build: permutari.o patrula.o
	g++ permutari.o -o permutari
	g++ patrula.o -o patrula

permutari.o: permutari.cpp
	g++ -c permutari.cpp

patrula.o: patrula.cpp
	g++ -c patrula.cpp

run-p1:
	./permutari		
run-p3:
	./patrula